server:
    port: 8765
spring:
    application:
        name: api-gateway
    cloud:
        discovery:
            enabled: true
        gateway:
            discovery:
                locator:
                    enabled: true
                    lower-case-service-id: true
            default-filters:
                - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
                - AddResponseHeader=Access-Control-Allow-Origin, *
            globalcors:
                cors-configurations:
                    "[/**]":
                        allowedOriginPatterns: "*"
                        allowCredentials: true
                        allowedMethods: "*"
                        allowedHeaders: "*"